### ISSUE TITLE
CentOS release enforcement in kickstart/yum configuration

### ISSUE THREAD

**Issue by pmuller** [kimor79/packer-centos#3]
Hello

Working on PR #1, I noticed this code in `etc/ks-update.cfg` : 
```
# 20151221: mirrorlist.centos.org doesn't return a list for release=7.2.1511
# but does for release=7.1.1503
mirror_works=`curl "http://mirrorlist.centos.org/?repo=os&arch=x86_64&release=${myrel}" | grep '^http://'`

if [ -n "${mirror_works}" ]; then
	mkdir -p /etc/yum/vars
	echo "${myrel}" > /etc/yum/vars/releasever
fi
```

I understand it should fix the CentOS release in yum's configuration, only when `mirrorlist.centos.org` answers the request.
When it doesn't, yum relies on its defaults, which will be the current CentOS release. Thus it will allow minor CentOS upgrades.
Is that right?

However, it doesn't work for 7.3.1611. And as of today, it doesn't work for 7.1.1503 either. Guess it worked earlier ?
From my understanding, it only works with `releasever=7`, and it returns a mirror list for the latest CentOS 7 release.

Any thoughts about this since commit 6b5ccf0b ?

**Comment by kimor79** [comment]
Yes, I think they changed CentOS so the notion of pinned minor versions doesn't really exist anymore. For most people, I think pinning at the major version is fine, but we ran into some packages that had breaking changes within minor CentOS versions. We mostly solve that now by using our own yum mirrors and staging updates to those mirrors.

**Comment by pmuller** [comment]
OK. I think I'll go with frozen mirrors too. Thanks. :)
